//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoverRetriever.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoverRetrieverResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoverRetrieverResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoverRetriever.Resources.CoverRetrieverResources", typeof(CoverRetrieverResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover of album {0} - {1}.
        /// </summary>
        public static string CoverPreviewTitle {
            get {
                return ResourceManager.GetString("CoverPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to all in the directory.
        /// </summary>
        public static string FlagApplyToAll {
            get {
                return ResourceManager.GetString("FlagApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed in the file.
        /// </summary>
        public static string FlagEmbedCover {
            get {
                return ResourceManager.GetString("FlagEmbedCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving tags for &apos;{0}&apos;....
        /// </summary>
        public static string GrabTagMessage {
            get {
                return ResourceManager.GetString("GrabTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the cover....
        /// </summary>
        public static string MessageCoverPreview {
            get {
                return ResourceManager.GetString("MessageCoverPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading covers....
        /// </summary>
        public static string MessageDownloadCover {
            get {
                return ResourceManager.GetString("MessageDownloadCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the library....
        /// </summary>
        public static string MessageLibraryLoad {
            get {
                return ResourceManager.GetString("MessageLibraryLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the cover....
        /// </summary>
        public static string MessageSaveCover {
            get {
                return ResourceManager.GetString("MessageSaveCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save tags in &apos;{0}&apos;.
        /// </summary>
        public static string MessageSaveTagsInContext {
            get {
                return ResourceManager.GetString("MessageSaveTagsInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album:.
        /// </summary>
        public static string TextAlbum {
            get {
                return ResourceManager.GetString("TextAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Retriever is a small, simple, easy to use application specially designed to help you find covers for compositions in &quot;MP3/FLAC&quot; formats and saving them onto disk or in audio file..
        /// </summary>
        public static string TextAppicationDescription {
            get {
                return ResourceManager.GetString("TextAppicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist:.
        /// </summary>
        public static string TextArtist {
            get {
                return ResourceManager.GetString("TextArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Anton Dimkov.
        /// </summary>
        public static string TextAuthor {
            get {
                return ResourceManager.GetString("TextAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string TextBrowse {
            get {
                return ResourceManager.GetString("TextBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current cover:.
        /// </summary>
        public static string TextCover {
            get {
                return ResourceManager.GetString("TextCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string TextCoverSixeHeight {
            get {
                return ResourceManager.GetString("TextCoverSixeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string TextCoverSixeWidth {
            get {
                return ResourceManager.GetString("TextCoverSixeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Info.
        /// </summary>
        public static string TextFileDetails {
            get {
                return ResourceManager.GetString("TextFileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve tags.
        /// </summary>
        public static string TextGetTagsFromLasrFm {
            get {
                return ResourceManager.GetString("TextGetTagsFromLasrFm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available: {0}.
        /// </summary>
        public static string TextNewVersion {
            get {
                return ResourceManager.GetString("TextNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TextOk {
            get {
                return ResourceManager.GetString("TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string TextOpenFolder {
            get {
                return ResourceManager.GetString("TextOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Retriever.
        /// </summary>
        public static string TextProduct {
            get {
                return ResourceManager.GetString("TextProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project home.
        /// </summary>
        public static string TextProjectHome {
            get {
                return ResourceManager.GetString("TextProjectHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TextSave {
            get {
                return ResourceManager.GetString("TextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System will load audio files to search for a cover from selected folder (including subfolders).
        /// </summary>
        public static string TextStepOne {
            get {
                return ResourceManager.GetString("TextStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1. Choose a folder with audio files.
        /// </summary>
        public static string TextStepOneHeader {
            get {
                return ResourceManager.GetString("TextStepOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System will load audio files to search for a cover from selected folder (including subfolders).
        /// </summary>
        public static string TextStepTwo {
            get {
                return ResourceManager.GetString("TextStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2. Choose a folder with audio files.
        /// </summary>
        public static string TextStepTwoHeader {
            get {
                return ResourceManager.GetString("TextStepTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag finder powered by:.
        /// </summary>
        public static string TextTaggerPoweredBy {
            get {
                return ResourceManager.GetString("TextTaggerPoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TextTrackName {
            get {
                return ResourceManager.GetString("TextTrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string TextYear {
            get {
                return ResourceManager.GetString("TextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a folder.
        /// </summary>
        public static string TitleStepOne {
            get {
                return ResourceManager.GetString("TitleStepOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a folder.
        /// </summary>
        public static string TitleStepTwo {
            get {
                return ResourceManager.GetString("TitleStepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to preview.
        /// </summary>
        public static string TooltipPreviewAction {
            get {
                return ResourceManager.GetString("TooltipPreviewAction", resourceCulture);
            }
        }
    }
}
